# Deployment for Alpine Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine-app
      zone: prod
  template:
    metadata:
      labels:
        app: alpine-app
        zone: prod
    spec:
      containers:
        - name: alpine-container
          image: alpine:latest
          command: ["sleep", "infinity"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"

---

# Deployment for Postgres Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres-app
      zone: prod
  template:
    metadata:
      labels:
        app: postgres-app
        zone: prod
    spec:
      containers:
        - name: postgres-container
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "supersecretpassword"
            - name: POSTGRES_DB
              value: "mydatabase"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---

# Deployment for Hello Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
      zone: prod
  template:
    metadata:
      labels:
        app: hello-app
        zone: prod
    spec:
      containers:
        - name: hello-container
          image: nigelpoulton/k8sbook:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
